---
language: ruby
rbenv:
  - 1.1.1
cache: bundler
addons:
  postgresql: '9.6'
before_script:
  - chmod +x setup_rncs_sources.sh
  - ./setup_rncs_sources.sh
  - psql -U postgres -f postgresql_setup.txt
  - psql -d rncs_worker_api_entreprise_test -f /usr/share/postgresql/9.6/extension/pgcrypto--1.3.sql
  - RAILS_ENV=test bundle exec rails db:migrate
script:
  - bundle exec rubocop
  - bundle exec rspec
